packages:
  - software
  - workflow
  - model
  - ui
  - block
  - test

catalog:
  '@platforma-sdk/block-tools': ^2.5.7
  '@platforma-sdk/model': ^1.22.2
  '@platforma-sdk/ui-vue': ^1.22.8
  '@platforma-sdk/tengo-builder': ^1.17.5
  '@platforma-sdk/workflow-tengo': ^2.9.9

  '@platforma-sdk/test': ^1.22.6
  '@milaboratories/graph-maker': ^1.1.33
  '@milaboratories/software-pframes-conv': ^2.1.7
  '@platforma-open/milaboratories.software-small-binaries': ^1.15.6
  '@platforma-open/milaboratories.software-subread': ^1.0.0
  '@platforma-open/milaboratories.software-star': ^1.0.1
  '@platforma-open/milaboratories.star-read-mapping.genome-asset': ^1.1.4
  '@platforma-open/milaboratories.runenv-r': ^1.2.14
  '@platforma-sdk/package-builder': ^2.15.0

  'vue': ^3.5.13
  'vue-tsc': ^2.2.0

  'typescript': ^5.7.3
  'tsup': ~8.3.6
  'turbo': ^2.3.4

  'vite': ^6.0.11
  'vitest': ^3.0.4
  '@vitejs/plugin-vue': ^5.2.1

  '@changesets/cli': ^2.27.12
