packages:
  - software
  - workflow
  - model
  - ui
  - block
  - test

catalog:
  '@platforma-sdk/block-tools': ^2.5.66
  '@platforma-sdk/model': ^1.37.4
  '@platforma-sdk/ui-vue': ^1.37.4
  '@platforma-sdk/tengo-builder': ^2.1.12
  '@platforma-sdk/workflow-tengo': ^4.9.3

  '@platforma-sdk/test': ^1.39.7
  '@milaboratories/graph-maker': ^1.1.131
  '@milaboratories/software-pframes-conv': ^2.2.2
  '@platforma-open/milaboratories.software-small-binaries': ^1.15.21
  '@platforma-open/milaboratories.runenv-r-differential-expression': ^1.0.7
  '@platforma-sdk/package-builder': ^2.16.2
  '@platforma-sdk/eslint-config': 1.0.1

  "@platforma-open/milaboratories.runenv-python-3": ^1.1.16

  'vue': ^3.5.13
  'vue-tsc': ^2.2.8

  'typescript': ~5.5.4
  'tsup': ~8.3.5
  'turbo': ^2.5.4

  'vite': ^6.3.5
  'vitest': ^2.1.8
  '@vitejs/plugin-vue': ^5.2.4

  '@changesets/cli': ^2.29.4