packages:
  - software
  - workflow
  - model
  - ui
  - block
  - test

catalog:
  '@platforma-sdk/block-tools': ^2.5.13
  '@platforma-sdk/model': ^1.22.18
  '@platforma-sdk/ui-vue': ^1.22.64
  '@platforma-sdk/tengo-builder': ^1.17.7
  '@platforma-sdk/workflow-tengo': ^2.13.5

  '@platforma-sdk/test': ^1.22.47
  '@milaboratories/graph-maker': ^1.1.51
  '@milaboratories/software-pframes-conv': ^2.1.12
  '@platforma-open/milaboratories.software-small-binaries': ^1.15.7
  '@platforma-open/milaboratories.software-subread': ^1.0.0
  '@platforma-open/milaboratories.software-star': ^1.0.1
  '@platforma-open/milaboratories.star-read-mapping.genome-asset': ^1.1.4
  '@platforma-open/milaboratories.runenv-r': ^1.2.17
  '@platforma-sdk/package-builder': ^2.15.0
  '@platforma-sdk/eslint-config': ^1.0.1

  'vue': ^3.5.13
  'vue-tsc': ^2.2.2

  'typescript': ^5.7.3
  'tsup': ~8.3.6
  'turbo': ^2.4.2

  'vite': ^6.1.0
  'vitest': ^3.0.5
  '@vitejs/plugin-vue': ^5.2.1

  '@changesets/cli': ^2.28.0
