packages:
  - software
  - workflow
  - model
  - ui
  - block
  - test

catalog:
  '@platforma-sdk/block-tools': ^2.5.18
  '@platforma-sdk/model': ^1.22.59
  '@platforma-sdk/ui-vue': ^1.22.82
  '@platforma-sdk/tengo-builder': ^1.19.2
  '@platforma-sdk/workflow-tengo': ^2.15.9

  '@platforma-sdk/test': ^1.22.86
  '@milaboratories/graph-maker': ^1.1.53
  '@milaboratories/software-pframes-conv': ^2.1.16
  '@platforma-open/milaboratories.software-small-binaries': ^1.15.14
  '@platforma-open/milaboratories.software-subread': ^1.0.0
  '@platforma-open/milaboratories.software-star': ^1.0.1
  '@platforma-open/milaboratories.star-read-mapping.genome-asset': ^1.1.4
  '@platforma-open/milaboratories.runenv-r-differential-expression': ^1.0.5
  '@platforma-sdk/package-builder': ^2.15.4
  '@platforma-sdk/eslint-config': ^1.0.1

  'vue': ^3.5.13
  'vue-tsc': ^2.2.2

  'typescript': ~5.5.4
  'tsup': ~8.4.0
  'turbo': ^2.4.4

  'vite': ^6.2.1
  'vitest': ^3.0.8
  '@vitejs/plugin-vue': ^5.2.1

  '@changesets/cli': ^2.28.1
