packages:
  - software
  - workflow
  - model
  - ui
  - block
  - test

catalog:
  '@platforma-sdk/block-tools': ^2.5.24
  '@platforma-sdk/model': ^1.24.5
  '@platforma-sdk/ui-vue': ^1.24.5
  '@platforma-sdk/tengo-builder': ^2.1.7
  '@platforma-sdk/workflow-tengo': ^4.7.1

  '@platforma-sdk/test': ^1.24.7
  '@milaboratories/graph-maker': ^1.1.64
  '@milaboratories/software-pframes-conv': ^2.1.19
  '@platforma-open/milaboratories.software-small-binaries': ^1.15.19
  '@platforma-open/milaboratories.runenv-r-differential-expression': ^1.0.7
  '@platforma-sdk/package-builder': ^2.15.6
  '@platforma-sdk/eslint-config': ^1.0.1

  "@platforma-open/milaboratories.runenv-python-3": ^1.1.7

  'vue': ^3.5.13
  'vue-tsc': ^2.2.2

  'typescript': ~5.5.4
  'tsup': ~8.4.0
  'turbo': ^2.4.4

  'vite': ^6.2.1
  'vitest': ^3.0.8
  '@vitejs/plugin-vue': ^5.2.1

  '@changesets/cli': ^2.28.1